### ISSUE TITLE
Regarding the Walker2d-Randparams Environment 

### ISSUE THREAD

**Issue by jonathanbrady88** [Rondorf/OMRL#1]
Thank you for your inspirational great work and open sourcing of the code. I have a question regarding the walker random environment. The walker can not walk when the reward is 800, this is the case for all the algorithms that use this environment. When doing a comparative analysis are we supposed only to compare the reward or is the reward scaled for this environment?

Have you observed a walking behavior when using the algorithms that use this environment?

**Comment by Rondorf** [comment]
Hi jonathanbrady88, unfortunately we didn't experiment with the Walker2D-RandParams environment so I can't really say. I think you should take a look at the "VariBAD" paper (and code), it might help you get your answer - https://arxiv.org/pdf/1910.08348.pdf
