### ISSUE TITLE
Multi-processing for online_training script 

### ISSUE THREAD

**Issue by SapanaChaudhary** [Rondorf/OMRL#2]
Hi, 

Is multi-processing functionality available for the online_training.py script? For me, for the same env, the BOReL code is taking much longer to run than VariBAD. 

Thank you!

**Comment by Rondorf** [comment]
Hi, 
Sorry for the late replay, I am not actively maintaining this repo. 
Regarding your question - unfortunately the script doesn't support multi-processing..
