### ISSUE TITLE
The number of tasks used in Cheetah-vel

### ISSUE THREAD

**Issue by nanzhu2003** [Rondorf/OMRL#3]
Hi, I'm trying to implement the code now, but I can't make sure how many tasks the environment of Cheetah-vel use as the paper. I would greatly thanks for your help!

**Comment by Rondorf** [comment]
Hi nanzhu2003,
We provide additional training details in the Appendix. Specifically, regarding the number of training tasks for 'Cheetah-vel', cf. the table in Appendix E --> we use 100 training tasks.
